### ISSUE TITLE
Breaking change in gptel: gptel-models as symbols

### ISSUE THREAD

**Issue by karthink** [lanceberge/elysium#4]
Just a heads-up that in preparation for media/images, function calling and json support in gptel, I now require `gptel-model` to be a symbol, i.e. `(setq gptel-model 'gpt-4o-mini)` instead of `(setq gptel-model "gpt-4o-mini")`.

While this is a breaking change, I'm trying to paper over this difference: specifying `gptel-model` as a string should still work fine, but with a warning.  Sorry for the trouble!

This will be effective in gptel version 0.9.5, which I'll be tagging today.  In a future version the warning will be upgraded to an error, hopefully giving everyone enough time to make the change.

**Comment by lanceberge** [comment]
Cool, thank you for letting me know!
